In [2]:
import pandas as pd
import numpy as np

In [3]:
"""
    numpy.concatenate()
"""

x = [1, 2, 3]
y = [4, 5, 6]
z = [7, 8, 9]

print(np.concatenate([x,y,z])) # 세로로 붙이는 것은 vstack(), 가로는 hstack()
print(np.vstack([x, y, z])) # 세로로 붙이기 위해서는 row, columm 존재하게 2차원으로 바꿔줘야함 .

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
"""
    pandas.concat()
    
"""
# 어떤 객체를 이어붙일지에 따라 pd, np 사용
# Pandas concat()은 np.concatenate()보다 다양한 옵션 제공
# Simply concatenate the tow Series objects

ser1 = pd.Series(['A', 'B', 'C'], index=[1, 2, 3]) # index 지정안하면 default는 정수 인덱스 0,1,2 ... 
ser2 = pd.Series(['D', 'E', 'F'], index=[4, 5, 6])

print(ser1, '\n\n', ser2)

print(pd.concat([ser1, ser2]))

1    A
2    B
3    C
dtype: object 

 4    D
5    E
6    F
dtype: object
1    A
2    B
3    C
4    D
5    E
6    F
dtype: object


In [7]:
# 
def make_df(cols, ind):
    data = {c: [str(c) + str(i) for i in ind]
            for c in cols}
    
    return pd.DataFrame(data, ind)

print(make_df('ABC', [1, 2]))

    A   B   C
1  A1  B1  C1
2  A2  B2  C2


In [8]:
# Concatenate the two DataFrame objects

df1 = make_df('AB', [1, 2])
df2 = make_df('AB', [3, 4])

print(pd.concat([df1, df2]))

    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4


In [12]:
df3 = make_df('AB', [0,1])
df4 = make_df('CD', [0,1])

print(df3, '\n\n', df4)

print(pd.concat([df3,df4]))
print(pd.concat([df3,df4], axis = 1))

# 인덱스 무시: ignore_index=True -> 0,1,0,1인덱스가 있어도 무시하고 새로운 인덱스를 부여하는 것
# 계층적 인덱싱 지원 : keys[keys] -> 인덱스 값 여러 개 두고 계층 줘서 인덱스 표현 가능

    A   B
0  A0  B0
1  A1  B1 

     C   D
0  C0  D0
1  C1  D1
     A    B    C    D
0   A0   B0  NaN  NaN
1   A1   B1  NaN  NaN
0  NaN  NaN   C0   D0
1  NaN  NaN   C1   D1
    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
