In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt # 이렇게 일부 라이브러리만 가져올 수 있음

In [4]:
# Creating a Numpy Array
lst = [1, 2, 3, 4]

arr = np.array(lst)
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [10]:
# .dtype attribute - numpy array가 가지고 있는 데이터 타입 알아보기

a = np.array([1.1, 1.2, 1.3])
b = np.array("1.1, 1.2, 1.3")
print(a.dtype) # 8바이트 길이를 갖는 실수 배열임을 확인 가능함
print(b.dtype) # U는 문자열이거나 타입 여러개 섞여있을 때 출력되는 데이터 타입

float64
<U13


In [12]:
"""
Size Comparison of ndarray and list objects
"""

from sys import getsizeof

lst = []
print(getsizeof(lst))

arr = np.array([])
print(getsizeof(arr))

"""기본 값은 numpy가 더 무겁지만 데이터를 넣었을 때 numpy는 값 그 자체가 들어가기 때문에
int형 값인 4byte만 들어가고 lst의 경우 4byte외에도 부가적인게 들어가서 메모리 오버헤드 발생""" 

lst = [1] # 56 -> 64
print(getsizeof(lst))

arr = np.array([1]) # 96 _> 100
print(getsizeof(arr))


56
96
64
100


In [14]:
"""
Operations with NumPy Arrays
"""
prices = [30, 25, 40, 20, 20, 35, 50, 35]
price_arr = np.array(prices)

# With a List
new_prices = [price - 5 for price in prices]
print(new_prices)

# With a ndarray
price_arr -= 5 # list연산에선 안됨
print(price_arr)

# **operation and np.sqrt

[25, 20, 35, 15, 15, 30, 45, 30]
[25 20 35 15 15 30 45 30]


In [29]:
"""
Exercise : test score
"""
test_1 = np.array([92, 94, 88, 91, 87])
test_2 = np.array([79, 100, 86, 93, 91])
test_3 = np.array([87, 85, 72, 90, 92])

test_3_fixed = test_3 + 2
print(test_3_fixed)

total_grade = test_1 + test_2 + test_3_fixed
print(total_grade)

final_grade = total_grade / 3
print(final_grade)

# 2차원 배열로 생각해보기
student_scores = np.array([test_1, test_2, test_3_fixed])
print(student_scores)

[89 87 74 92 94]
[260 281 248 276 272]
[86.66666667 93.66666667 82.66666667 92.         90.66666667]
[[ 92  94  88  91  87]
 [ 79 100  86  93  91]
 [ 89  87  74  92  94]]


In [37]:
jeremy_test_2 = student_scores[1,3]
manual_adwoa_test_1 = np.array([student_scores[0,1], student_scores[0, 2]])
print(manual_adwoa_test_1)

print(student_scores[:,4]) # [:,-1] 해도 됨

[94 88]


In [48]:
"""
Logical Operations with Arrays
"""
# masking - mask는 논리연산을 통해 정해진 boolean값임.
a = np.array([10, 2, 2, 4, 5, 3, 9, 8, 9, 7])
a > 5
mask = a > 5
print(mask)

# select using Logical operations - 논리식 만족하는 부분집합 구할 때 씀
selected = a[a > 5]
print(selected)

# combined Logical operations

selected = a[(a > 5) | (a < 4)]
print(selected)

selected = a[(a >4) & (a < 7)]
print(selected)

[ True False False False False False  True  True  True  True]
[10  9  8  9  7]
[10  2  2  3  9  8  9  7]
[5]


In [66]:
"""
Exercise 골디락스 포리지(죽)페스티벌
"""

porridge = np.array([79, 65, 50, 63, 56, 90, 85, 98, 79, 51])

cold = porridge[porridge < 60]
hot = porridge [porridge > 80]
just_right = porridge[(porridge >= 60) &  (porridge <= 80)]

print(cold, hot, just_right)

[50 56 51] [90 85 98] [79 65 63 79]
