In [2]:
import numpy as np

In [3]:
"""
Computing reciprocals in loops
"""

# Function for computing reciprocals using Looping
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1, 10, size=5)
print(values)

compute_reciprocals(values)

[7 6 7 8 8]


array([0.14285714, 0.16666667, 0.14285714, 0.125     , 0.125     ])

In [4]:
"""
Comparisom: Loop vs ufuncs(vectorized)
"""

big_array = np.random.randint(1, 100, size=1000000)

# Looping on a big array
%timeit compute_reciprocals(big_array) # 특정 시간 측정하고 평균적으로 출력 - 주피터에서 제공(파이썬에서 제공X, 매직함수라고 부름)

# 1000000의 역수 for문으로 구했을 떄 2.04초 걸림

2.23 s ± 231 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [5]:
# Vectorized operations
%timeit 1 / big_array # 스칼라와 벡터로 100만개 역수로 구함 / 훨씬 빠름

3.48 ms ± 212 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [6]:
"""
numpy.ufunc
"""

np.random.seed(1)
arr1 = np.random.randint(10, size=(5))
arr2 = np.random.randint(10, size=(5))
print(arr1,arr2)

arr1 = arr1 - 2
print(arr1)

arr3 = arr1 + arr2
print(arr3)

arr4 = np.random.randint(10, size=(3, 5)) # 다차원연산도 됨
print(arr4)


[5 8 9 5 0] [0 1 7 6 9]
[ 3  6  7  3 -2]
[ 3  7 14  9  7]
[[2 4 5 2 4]
 [2 4 7 7 9]
 [1 7 0 6 9]]


In [8]:
"""
UFuncs : Array Arithmetic
"""

# Basic arithmetic operations on an array
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x ** 2 =", x ** 2)

# 일일이 유니버설 함수 외울필요는 없음

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x ** 2 = [0 1 4 9]


In [14]:
"""
UFuncs: Absolute Value
"""

x = np.array([-2, -1, 0, 1, 2])
print(np.abs(x))

x = np.array([3-4j, 4-3j, 2+0j, 0+1j])
print(np.abs(x))

[2 1 0 1 2]
[5. 5. 2. 1.]


In [25]:
"""
URuncs: Trigonometric Functions
"""
# 시작값과 끝값 인자로 받고 몇 개로 나눌지

theta = np.linspace(0, np.pi, 3)

print(theta)

print(np.sin(theta))


[0.         1.57079633 3.14159265]


In [30]:
"""
UFuncs: Aggregation
"""
# 집계함수로 기술통계(최댓값, 최솟값 등 기초 통계 구하는 과정이 기술통계) 가능
# reduce() 중요!!!
# 특정 연산으로 축소 = 3X4를 하나의 값으로 표현(값이 스칼라로 나옴)
x = np.arange(1, 5)
print(x)

aggr = np.add.reduce(x)
print(aggr)

aggr = np.multiply.reduce(x)
print(aggr)

[1 2 3 4]
10
24


In [18]:
# accumulate()
# 집계함수
x = np.arange(1, 15)
# print(x)

accum = np.add.accumulate(x)
# print(accum)
accum = np.multiply.accumulate(x)
# print(accum)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[  1   3   6  10  15  21  28  36  45  55  66  78  91 105]
[         1          2          6         24        120        720
       5040      40320     362880    3628800   39916800  479001600
 1932053504 1278945280]


In [19]:
# Summing the Values in an Array
# 배열 합계 계산***
# np.sum()

np.random.seed(2)
arr = np.random.rand(1000000) # rand() : create 0~1 real Values

print(arr)
print('sum=', np.sum(arr))

%timeit sum(arr) # 실행시간. 파이썬 내장 함수

[0.4359949  0.02592623 0.54966248 ... 0.78483191 0.00778062 0.42442656]
sum= 499468.5166853333
132 ms ± 8.52 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [20]:
%timeit np.sum(arr) # 파이썬 뭄법보다 numpy가 훨씬 빠름

885 µs ± 29 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [44]:
# Other Aggr. functions
print("max = ", np.max(arr))
print("min = ", np.min(arr))
print("mean = ", np.mean(arr))
print("median = ", np.median(arr))
print("percentile = ", np.percentile(arr,90))
print(np.any(arr>1))
print(np.all(arr>0))

max =  0.9999976661165695
min =  9.475783189216713e-07
mean =  0.49946851668533326
median =  0.49948650836352526
percentile =  0.9004310892470595
False
True


In [21]:
# Multi dimensional aggregates

np.random.seed(5)

arr = np.random.randint(10, size=(3,4))
print(arr)

print(np.sum(arr, axis=0))
print(np.sum(arr, axis=1))

[[3 6 6 0]
 [9 8 4 7]
 [0 0 7 1]]
[12 14 17  8]
[15 28  8]
